sudo: false

language: ruby

rvm:
  - 2.4.0

before_install:
  - gem update --system
  - gem install bundler

cache: bundler
script: bundle exec middleman build
deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
